name: Release downloader

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Set the proper version name to be used `v1` etc. Defaults: v1'
        default: v1

jobs:
  start-release:
    runs-on: ubuntu-latest
    steps:
      - name: Update the release notes.
        uses: appsfortableau/github-action-releaser@v1
        with:
          tag_name: '${{ inputs.VERSION }}'
          token: '${{ github.token }}'
          move_tag: true
